[config]
schemaVersion = "0.0.1"

[package]
namespace = "N00byKing"
name = "NineSolsTracker"
versionNumber = "0.1.0"
description = "Item Tracker for Nine Sols."
websiteUrl = "https://github.com/N00byKing/NineSolsTracker"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
